apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  OPENAI_API_KEY: <base64-encoded-key>
  PINECONE_API_KEY: <base64-encoded-key>
  LANGTRACE_API_KEY: <base64-encoded-key>
  FLASK_SECRET_KEY: <base64-encoded-key>
  SERPAPI_API_KEY: <base64-encoded-key>