apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: your-registry/your-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openai-api-key
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: pinecone-api-key
        - name: LANGTRACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: langtrace-api-key
        - name: INDEX_NAME
          value: "pdf-vectors"
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: flask-secret-key
        volumeMounts:
        - name: pdf-data
          mountPath: /app/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: pdf-data
        emptyDir: {}