apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: us-central1-docker.pkg.dev/gpuchase-test/ragregistry/rag-chatbot:<tag>
        resources:
          requests:
            cpu: "500m"  # 0.5 vCPU requested
            memory: "1Gi"  # 1 GiB memory requested
          limits:
            cpu: "1000m"  # 1 vCPU max limit
            memory: "2Gi"  # 2 GiB memory max limit
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PINECONE_API_KEY
        - name: LANGTRACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: LANGTRACE_API_KEY
        - name: INDEX_NAME
          value: "research-chatbot-index"
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: FLASK_SECRET_KEY
        volumeMounts:
        - name: pdf-data
          mountPath: /app/data
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: pdf-data
        emptyDir: {}