apiVersion: batch/v1
kind: Job
metadata:
  name: data-ingestion
spec:
  template:
    spec:
      containers:
      - name: data-ingestion
        image: your-registry/your-app:latest
        imagePullPolicy: Always
        command: ["python", "data_ingestion.py"]
        env:
        - name: ENVIRONMENT
            value: "production"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openai-api-key
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: pinecone-api-key
        - name: LANGTRACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: langtrace-api-key
        - name: INDEX_NAME
          value: "pdf-vectors"
        volumeMounts:
        - name: pdf-data
          mountPath: /app/data
      volumes:
      - name: pdf-data
        emptyDir: {}
      restartPolicy: Never