apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  openai-api-key: c2stcHJvai1fa1l0bEoxRlZ6OXZVUlZwOHBuTXp3ZzdaZkVLeVpWU09CQjVVRE43Tm56Ymo0VVpRSlRtczFWZy0xSlpBMDg3U1NjZjFicEZSNlQzQmxia0ZKbEx6aXpIb2EwdmFiNlphVkF6ZzF3cmluM0hxSGpOUTZlMmZTNlNPN3VHZEFVR0x4Y1BYTkdGdEdFcHl2YV9aSXhITmg5bXoyVUE=
  pinecone-api-key: cGNza180dXBtandfSkxBZnhMS2VyNWNiS0ZRaWY5OUFHYWdaV016UEhxUlZzTjdZcnJZWjl6TGI5emJMNU1SVlVWekpENlMxcmdO
  langtrace-api-key: ZDNlNDM0YmUyNjMwOGYyYzA2NmM4Zjk5NDA0NjRjZWRkOTZlNzhmZTAyYzUwZDM4YmYzNzAwNjNmNGIyYzRhNg==
  flask-secret-key: MzBKTzmAjTasch+yPPe0pn2nhuOeNNvm