apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  openai-api-key: <base64-encoded-key>
  pinecone-api-key: <base64-encoded-key>
  langtrace-api-key: <base64-encoded-key>
  flask-secret-key: MzBKTzmAjTasch+yPPe0pn2nhuOeNNvm